/**
 * (C) Multitude Corporation 2024
 * generated by Xtext 2.33.0
 from BLESS.xtext, by BRL 
 * All Rights Reserved.
 * 
 * NO WARRANTY. ALL MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. 
 * 
 * This program and the accompanying materials are made available under the terms of the 
 * Creative Commons Attribution-NoDerivatives 4.0 International Public License
 * which is available at https://creativecommons.org/licenses/by-nd/4.0/ 
 *  
 * This program includes and/or can make use of certain third party source code, object code, documentation and other
 * files ("Third Party Software"). The Third Party Software that is used by this program is dependent upon your system
 * configuration. By using this program, You agree to comply with any and all relevant Third Party Software terms and
 * conditions contained in any such Third Party Software or separate license file distributed with such Third Party
 * Software. The parties who own the Third Party Software ("Third Party Licensors") are intended third party benefici-
 * aries to this license with respect to the terms applicable to their Third Party Software. Third Party Software li-
 * censes only apply to the Third Party Software and not any other portion of this program or this program as a whole.
 */
package com.multitude.aadl.bless.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class BLESSOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
