/**
 * (C) Multitude Corporation 2024
 * generated by Xtext 2.30.0
 *  from BLESS.xtext, by BRL
 */
package com.multitude.aadl.bless.bLESS;

import org.eclipse.emf.ecore.EObject;

import org.osate.aadl2.Element;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assertion Numeric Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getAssertionNumericExpression()
 * @model
 * @generated
 */
public interface AssertionNumericExpression extends EObject, Element
{
} // AssertionNumericExpression
