/**
 * (C) Multitude Corporation 2023
 * generated by Xtext 2.30.0
 *  from BLESS.xtext, by BRL
 */
package com.multitude.aadl.bless.bLESS;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.osate.aadl2.AnnexLibrary;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assertion Library</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.multitude.aadl.bless.bLESS.AssertionLibrary#getGhosts <em>Ghosts</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.AssertionLibrary#getAssertion_list <em>Assertion list</em>}</li>
 * </ul>
 *
 * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getAssertionLibrary()
 * @model
 * @generated
 */
public interface AssertionLibrary extends EObject, AnnexLibrary
{
  /**
   * Returns the value of the '<em><b>Ghosts</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ghosts</em>' containment reference.
   * @see #setGhosts(GhostVariables)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getAssertionLibrary_Ghosts()
   * @model containment="true"
   * @generated
   */
  GhostVariables getGhosts();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.AssertionLibrary#getGhosts <em>Ghosts</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ghosts</em>' containment reference.
   * @see #getGhosts()
   * @generated
   */
  void setGhosts(GhostVariables value);

  /**
   * Returns the value of the '<em><b>Assertion list</b></em>' containment reference list.
   * The list contents are of type {@link com.multitude.aadl.bless.bLESS.NamedAssertion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assertion list</em>' containment reference list.
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getAssertionLibrary_Assertion_list()
   * @model containment="true"
   * @generated
   */
  EList<NamedAssertion> getAssertion_list();

} // AssertionLibrary
