/**
 * (C) Multitude Corporation 2023
 * generated by Xtext 2.27.0
 *  from BLESS.xtext, by BRL
 */
package com.multitude.aadl.bless.bLESS;

import org.eclipse.emf.ecore.EObject;

import org.osate.aadl2.Element;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Behavior Time</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BehaviorTime#getQuantity <em>Quantity</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BehaviorTime#getValue <em>Value</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BehaviorTime#getDuration <em>Duration</em>}</li>
 * </ul>
 *
 * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorTime()
 * @model
 * @generated
 */
public interface BehaviorTime extends EObject, Element
{
  /**
   * Returns the value of the '<em><b>Quantity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantity</em>' containment reference.
   * @see #setQuantity(Quantity)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorTime_Quantity()
   * @model containment="true"
   * @generated
   */
  Quantity getQuantity();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BehaviorTime#getQuantity <em>Quantity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantity</em>' containment reference.
   * @see #getQuantity()
   * @generated
   */
  void setQuantity(Quantity value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(ValueName)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorTime_Value()
   * @model containment="true"
   * @generated
   */
  ValueName getValue();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BehaviorTime#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(ValueName value);

  /**
   * Returns the value of the '<em><b>Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' containment reference.
   * @see #setDuration(ParenthesizedSubexpression)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorTime_Duration()
   * @model containment="true"
   * @generated
   */
  ParenthesizedSubexpression getDuration();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BehaviorTime#getDuration <em>Duration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' containment reference.
   * @see #getDuration()
   * @generated
   */
  void setDuration(ParenthesizedSubexpression value);

} // BehaviorTime
