/**
 * (C) Multitude Corporation 2023
 * generated by Xtext 2.30.0
 *  from BLESS.xtext, by BRL
 */
package com.multitude.aadl.bless.bLESS;

import org.eclipse.emf.ecore.EObject;

import org.osate.aadl2.NamedElement;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Behavior State</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BehaviorState#isInitial <em>Initial</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BehaviorState#isComplete <em>Complete</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BehaviorState#isFinal <em>Final</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BehaviorState#isMode <em>Mode</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BehaviorState#getState_assertion <em>State assertion</em>}</li>
 * </ul>
 *
 * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorState()
 * @model
 * @generated
 */
public interface BehaviorState extends EObject, NamedElement
{
  /**
   * Returns the value of the '<em><b>Initial</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initial</em>' attribute.
   * @see #setInitial(boolean)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorState_Initial()
   * @model
   * @generated
   */
  boolean isInitial();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BehaviorState#isInitial <em>Initial</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initial</em>' attribute.
   * @see #isInitial()
   * @generated
   */
  void setInitial(boolean value);

  /**
   * Returns the value of the '<em><b>Complete</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Complete</em>' attribute.
   * @see #setComplete(boolean)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorState_Complete()
   * @model
   * @generated
   */
  boolean isComplete();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BehaviorState#isComplete <em>Complete</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Complete</em>' attribute.
   * @see #isComplete()
   * @generated
   */
  void setComplete(boolean value);

  /**
   * Returns the value of the '<em><b>Final</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Final</em>' attribute.
   * @see #setFinal(boolean)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorState_Final()
   * @model
   * @generated
   */
  boolean isFinal();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BehaviorState#isFinal <em>Final</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Final</em>' attribute.
   * @see #isFinal()
   * @generated
   */
  void setFinal(boolean value);

  /**
   * Returns the value of the '<em><b>Mode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mode</em>' attribute.
   * @see #setMode(boolean)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorState_Mode()
   * @model
   * @generated
   */
  boolean isMode();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BehaviorState#isMode <em>Mode</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mode</em>' attribute.
   * @see #isMode()
   * @generated
   */
  void setMode(boolean value);

  /**
   * Returns the value of the '<em><b>State assertion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>State assertion</em>' containment reference.
   * @see #setState_assertion(Assertion)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorState_State_assertion()
   * @model containment="true"
   * @generated
   */
  Assertion getState_assertion();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BehaviorState#getState_assertion <em>State assertion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State assertion</em>' containment reference.
   * @see #getState_assertion()
   * @generated
   */
  void setState_assertion(Assertion value);

} // BehaviorState
