/**
 * (C) Multitude Corporation 2021
 * generated by Xtext 2.27.0
 *  from BLESS.xtext, by BRL
 */
package com.multitude.aadl.bless.bLESS;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.osate.aadl2.NamedElement;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Behavior Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BehaviorTransition#getPriority <em>Priority</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BehaviorTransition#getColon <em>Colon</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BehaviorTransition#getSources <em>Sources</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BehaviorTransition#getDispatch <em>Dispatch</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BehaviorTransition#getExecute <em>Execute</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BehaviorTransition#getMode <em>Mode</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BehaviorTransition#getInternal <em>Internal</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BehaviorTransition#getDestination <em>Destination</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BehaviorTransition#getActions <em>Actions</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BehaviorTransition#getAss <em>Ass</em>}</li>
 * </ul>
 *
 * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorTransition()
 * @model
 * @generated
 */
public interface BehaviorTransition extends EObject, NamedElement
{
  /**
   * Returns the value of the '<em><b>Priority</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Priority</em>' containment reference.
   * @see #setPriority(Priority)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorTransition_Priority()
   * @model containment="true"
   * @generated
   */
  Priority getPriority();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BehaviorTransition#getPriority <em>Priority</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Priority</em>' containment reference.
   * @see #getPriority()
   * @generated
   */
  void setPriority(Priority value);

  /**
   * Returns the value of the '<em><b>Colon</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Colon</em>' attribute.
   * @see #setColon(String)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorTransition_Colon()
   * @model
   * @generated
   */
  String getColon();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BehaviorTransition#getColon <em>Colon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Colon</em>' attribute.
   * @see #getColon()
   * @generated
   */
  void setColon(String value);

  /**
   * Returns the value of the '<em><b>Sources</b></em>' reference list.
   * The list contents are of type {@link com.multitude.aadl.bless.bLESS.BehaviorState}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sources</em>' reference list.
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorTransition_Sources()
   * @model
   * @generated
   */
  EList<BehaviorState> getSources();

  /**
   * Returns the value of the '<em><b>Dispatch</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dispatch</em>' containment reference.
   * @see #setDispatch(DispatchCondition)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorTransition_Dispatch()
   * @model containment="true"
   * @generated
   */
  DispatchCondition getDispatch();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BehaviorTransition#getDispatch <em>Dispatch</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dispatch</em>' containment reference.
   * @see #getDispatch()
   * @generated
   */
  void setDispatch(DispatchCondition value);

  /**
   * Returns the value of the '<em><b>Execute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Execute</em>' containment reference.
   * @see #setExecute(ExecuteCondition)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorTransition_Execute()
   * @model containment="true"
   * @generated
   */
  ExecuteCondition getExecute();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BehaviorTransition#getExecute <em>Execute</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Execute</em>' containment reference.
   * @see #getExecute()
   * @generated
   */
  void setExecute(ExecuteCondition value);

  /**
   * Returns the value of the '<em><b>Mode</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mode</em>' containment reference.
   * @see #setMode(ModeCondition)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorTransition_Mode()
   * @model containment="true"
   * @generated
   */
  ModeCondition getMode();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BehaviorTransition#getMode <em>Mode</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mode</em>' containment reference.
   * @see #getMode()
   * @generated
   */
  void setMode(ModeCondition value);

  /**
   * Returns the value of the '<em><b>Internal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Internal</em>' containment reference.
   * @see #setInternal(InternalCondition)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorTransition_Internal()
   * @model containment="true"
   * @generated
   */
  InternalCondition getInternal();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BehaviorTransition#getInternal <em>Internal</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Internal</em>' containment reference.
   * @see #getInternal()
   * @generated
   */
  void setInternal(InternalCondition value);

  /**
   * Returns the value of the '<em><b>Destination</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Destination</em>' reference.
   * @see #setDestination(BehaviorState)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorTransition_Destination()
   * @model
   * @generated
   */
  BehaviorState getDestination();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BehaviorTransition#getDestination <em>Destination</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Destination</em>' reference.
   * @see #getDestination()
   * @generated
   */
  void setDestination(BehaviorState value);

  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference.
   * @see #setActions(BehaviorActions)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorTransition_Actions()
   * @model containment="true"
   * @generated
   */
  BehaviorActions getActions();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BehaviorTransition#getActions <em>Actions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Actions</em>' containment reference.
   * @see #getActions()
   * @generated
   */
  void setActions(BehaviorActions value);

  /**
   * Returns the value of the '<em><b>Ass</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ass</em>' containment reference.
   * @see #setAss(Assertion)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBehaviorTransition_Ass()
   * @model containment="true"
   * @generated
   */
  Assertion getAss();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BehaviorTransition#getAss <em>Ass</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ass</em>' containment reference.
   * @see #getAss()
   * @generated
   */
  void setAss(Assertion value);

} // BehaviorTransition
