/**
 * (C) Multitude Corporation 2024
 * generated by Xtext 2.33.0
 *  from BLESS.xtext, by BRL
 */
package com.multitude.aadl.bless.bLESS;

import org.eclipse.emf.ecore.EObject;

import org.osate.aadl2.AnnexSubclause;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Subclause</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BLESSSubclause#isNo_proof <em>No proof</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BLESSSubclause#getAssert_clause <em>Assert clause</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BLESSSubclause#getInvariant <em>Invariant</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BLESSSubclause#getVariables <em>Variables</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BLESSSubclause#getStatesSection <em>States Section</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.BLESSSubclause#getTransitions <em>Transitions</em>}</li>
 * </ul>
 *
 * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBLESSSubclause()
 * @model
 * @generated
 */
public interface BLESSSubclause extends EObject, AnnexSubclause
{
  /**
   * Returns the value of the '<em><b>No proof</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>No proof</em>' attribute.
   * @see #setNo_proof(boolean)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBLESSSubclause_No_proof()
   * @model
   * @generated
   */
  boolean isNo_proof();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BLESSSubclause#isNo_proof <em>No proof</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>No proof</em>' attribute.
   * @see #isNo_proof()
   * @generated
   */
  void setNo_proof(boolean value);

  /**
   * Returns the value of the '<em><b>Assert clause</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assert clause</em>' containment reference.
   * @see #setAssert_clause(AssertClause)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBLESSSubclause_Assert_clause()
   * @model containment="true"
   * @generated
   */
  AssertClause getAssert_clause();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BLESSSubclause#getAssert_clause <em>Assert clause</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assert clause</em>' containment reference.
   * @see #getAssert_clause()
   * @generated
   */
  void setAssert_clause(AssertClause value);

  /**
   * Returns the value of the '<em><b>Invariant</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Invariant</em>' containment reference.
   * @see #setInvariant(InvariantClause)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBLESSSubclause_Invariant()
   * @model containment="true"
   * @generated
   */
  InvariantClause getInvariant();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BLESSSubclause#getInvariant <em>Invariant</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Invariant</em>' containment reference.
   * @see #getInvariant()
   * @generated
   */
  void setInvariant(InvariantClause value);

  /**
   * Returns the value of the '<em><b>Variables</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variables</em>' containment reference.
   * @see #setVariables(VariablesSection)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBLESSSubclause_Variables()
   * @model containment="true"
   * @generated
   */
  VariablesSection getVariables();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BLESSSubclause#getVariables <em>Variables</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variables</em>' containment reference.
   * @see #getVariables()
   * @generated
   */
  void setVariables(VariablesSection value);

  /**
   * Returns the value of the '<em><b>States Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>States Section</em>' containment reference.
   * @see #setStatesSection(StatesSection)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBLESSSubclause_StatesSection()
   * @model containment="true"
   * @generated
   */
  StatesSection getStatesSection();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BLESSSubclause#getStatesSection <em>States Section</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>States Section</em>' containment reference.
   * @see #getStatesSection()
   * @generated
   */
  void setStatesSection(StatesSection value);

  /**
   * Returns the value of the '<em><b>Transitions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transitions</em>' containment reference.
   * @see #setTransitions(Transitions)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getBLESSSubclause_Transitions()
   * @model containment="true"
   * @generated
   */
  Transitions getTransitions();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.BLESSSubclause#getTransitions <em>Transitions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transitions</em>' containment reference.
   * @see #getTransitions()
   * @generated
   */
  void setTransitions(Transitions value);

} // BLESSSubclause
