/**
 * (C) Multitude Corporation 2023
 * generated by Xtext 2.30.0
 *  from BLESS.xtext, by BRL
 */
package com.multitude.aadl.bless.bLESS;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.osate.aadl2.Element;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Catch Clause Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.multitude.aadl.bless.bLESS.CatchClauseTerm#getExceptions <em>Exceptions</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.CatchClauseTerm#isAll <em>All</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.CatchClauseTerm#getAction <em>Action</em>}</li>
 * </ul>
 *
 * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getCatchClauseTerm()
 * @model
 * @generated
 */
public interface CatchClauseTerm extends EObject, Element
{
  /**
   * Returns the value of the '<em><b>Exceptions</b></em>' reference list.
   * The list contents are of type {@link com.multitude.aadl.bless.bLESS.Exception}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exceptions</em>' reference list.
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getCatchClauseTerm_Exceptions()
   * @model
   * @generated
   */
  EList<com.multitude.aadl.bless.bLESS.Exception> getExceptions();

  /**
   * Returns the value of the '<em><b>All</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>All</em>' attribute.
   * @see #setAll(boolean)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getCatchClauseTerm_All()
   * @model
   * @generated
   */
  boolean isAll();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.CatchClauseTerm#isAll <em>All</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>All</em>' attribute.
   * @see #isAll()
   * @generated
   */
  void setAll(boolean value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' containment reference.
   * @see #setAction(BasicAction)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getCatchClauseTerm_Action()
   * @model containment="true"
   * @generated
   */
  BasicAction getAction();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.CatchClauseTerm#getAction <em>Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' containment reference.
   * @see #getAction()
   * @generated
   */
  void setAction(BasicAction value);

} // CatchClauseTerm
