/**
 * (C) Multitude Corporation 2024
 * generated by Xtext 2.33.0
 *  from BLESS.xtext, by BRL
 */
package com.multitude.aadl.bless.bLESS;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.osate.aadl2.ComponentClassifier;
import org.osate.aadl2.Element;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Computation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.multitude.aadl.bless.bLESS.Computation#getLb <em>Lb</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.Computation#getUb <em>Ub</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.Computation#getComponent <em>Component</em>}</li>
 * </ul>
 *
 * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getComputation()
 * @model
 * @generated
 */
public interface Computation extends EObject, Element
{
  /**
   * Returns the value of the '<em><b>Lb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lb</em>' containment reference.
   * @see #setLb(BehaviorTime)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getComputation_Lb()
   * @model containment="true"
   * @generated
   */
  BehaviorTime getLb();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.Computation#getLb <em>Lb</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lb</em>' containment reference.
   * @see #getLb()
   * @generated
   */
  void setLb(BehaviorTime value);

  /**
   * Returns the value of the '<em><b>Ub</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ub</em>' containment reference.
   * @see #setUb(BehaviorTime)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getComputation_Ub()
   * @model containment="true"
   * @generated
   */
  BehaviorTime getUb();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.Computation#getUb <em>Ub</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ub</em>' containment reference.
   * @see #getUb()
   * @generated
   */
  void setUb(BehaviorTime value);

  /**
   * Returns the value of the '<em><b>Component</b></em>' reference list.
   * The list contents are of type {@link org.osate.aadl2.ComponentClassifier}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component</em>' reference list.
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getComputation_Component()
   * @model
   * @generated
   */
  EList<ComponentClassifier> getComponent();

} // Computation
