/**
 * (C) Multitude Corporation 2023
 * generated by Xtext 2.27.0
 *  from BLESS.xtext, by BRL
 */
package com.multitude.aadl.bless.bLESS;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.osate.aadl2.Element;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conjunction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.multitude.aadl.bless.bLESS.Conjunction#getL <em>L</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.Conjunction#getSym <em>Sym</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.Conjunction#getR <em>R</em>}</li>
 * </ul>
 *
 * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getConjunction()
 * @model
 * @generated
 */
public interface Conjunction extends EObject, Element
{
  /**
   * Returns the value of the '<em><b>L</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>L</em>' containment reference.
   * @see #setL(Relation)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getConjunction_L()
   * @model containment="true"
   * @generated
   */
  Relation getL();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.Conjunction#getL <em>L</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>L</em>' containment reference.
   * @see #getL()
   * @generated
   */
  void setL(Relation value);

  /**
   * Returns the value of the '<em><b>Sym</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sym</em>' attribute.
   * @see #setSym(String)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getConjunction_Sym()
   * @model
   * @generated
   */
  String getSym();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.Conjunction#getSym <em>Sym</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sym</em>' attribute.
   * @see #getSym()
   * @generated
   */
  void setSym(String value);

  /**
   * Returns the value of the '<em><b>R</b></em>' containment reference list.
   * The list contents are of type {@link com.multitude.aadl.bless.bLESS.Relation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>R</em>' containment reference list.
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getConjunction_R()
   * @model containment="true"
   * @generated
   */
  EList<Relation> getR();

} // Conjunction
