/**
 * (C) Multitude Corporation 2024
 * generated by Xtext 2.33.0
 *  from BLESS.xtext, by BRL
 */
package com.multitude.aadl.bless.bLESS;

import org.eclipse.emf.ecore.EObject;

import org.osate.aadl2.Element;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Counting Quantification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.multitude.aadl.bless.bLESS.CountingQuantification#getVariables <em>Variables</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.CountingQuantification#isIn <em>In</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.CountingQuantification#getRange <em>Range</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.CountingQuantification#isWhich <em>Which</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.CountingQuantification#getCondition <em>Condition</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.CountingQuantification#getCounted <em>Counted</em>}</li>
 * </ul>
 *
 * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getCountingQuantification()
 * @model
 * @generated
 */
public interface CountingQuantification extends EObject, Element
{
  /**
   * Returns the value of the '<em><b>Variables</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variables</em>' containment reference.
   * @see #setVariables(LogicVariables)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getCountingQuantification_Variables()
   * @model containment="true"
   * @generated
   */
  LogicVariables getVariables();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.CountingQuantification#getVariables <em>Variables</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variables</em>' containment reference.
   * @see #getVariables()
   * @generated
   */
  void setVariables(LogicVariables value);

  /**
   * Returns the value of the '<em><b>In</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>In</em>' attribute.
   * @see #setIn(boolean)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getCountingQuantification_In()
   * @model
   * @generated
   */
  boolean isIn();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.CountingQuantification#isIn <em>In</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>In</em>' attribute.
   * @see #isIn()
   * @generated
   */
  void setIn(boolean value);

  /**
   * Returns the value of the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Range</em>' containment reference.
   * @see #setRange(Range)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getCountingQuantification_Range()
   * @model containment="true"
   * @generated
   */
  Range getRange();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.CountingQuantification#getRange <em>Range</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Range</em>' containment reference.
   * @see #getRange()
   * @generated
   */
  void setRange(Range value);

  /**
   * Returns the value of the '<em><b>Which</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Which</em>' attribute.
   * @see #setWhich(boolean)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getCountingQuantification_Which()
   * @model
   * @generated
   */
  boolean isWhich();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.CountingQuantification#isWhich <em>Which</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Which</em>' attribute.
   * @see #isWhich()
   * @generated
   */
  void setWhich(boolean value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Predicate)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getCountingQuantification_Condition()
   * @model containment="true"
   * @generated
   */
  Predicate getCondition();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.CountingQuantification#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Predicate value);

  /**
   * Returns the value of the '<em><b>Counted</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Counted</em>' containment reference.
   * @see #setCounted(Predicate)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getCountingQuantification_Counted()
   * @model containment="true"
   * @generated
   */
  Predicate getCounted();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.CountingQuantification#getCounted <em>Counted</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Counted</em>' containment reference.
   * @see #getCounted()
   * @generated
   */
  void setCounted(Predicate value);

} // CountingQuantification
