/**
 * (C) Multitude Corporation 2023
 * generated by Xtext 2.30.0
 *  from BLESS.xtext, by BRL
 */
package com.multitude.aadl.bless.bLESS;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.osate.aadl2.Element;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dispatch Conjunction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.multitude.aadl.bless.bLESS.DispatchConjunction#getTrigger <em>Trigger</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.DispatchConjunction#isAnd <em>And</em>}</li>
 * </ul>
 *
 * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getDispatchConjunction()
 * @model
 * @generated
 */
public interface DispatchConjunction extends EObject, Element
{
  /**
   * Returns the value of the '<em><b>Trigger</b></em>' containment reference list.
   * The list contents are of type {@link com.multitude.aadl.bless.bLESS.DispatchTrigger}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trigger</em>' containment reference list.
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getDispatchConjunction_Trigger()
   * @model containment="true"
   * @generated
   */
  EList<DispatchTrigger> getTrigger();

  /**
   * Returns the value of the '<em><b>And</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>And</em>' attribute.
   * @see #setAnd(boolean)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getDispatchConjunction_And()
   * @model
   * @generated
   */
  boolean isAnd();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.DispatchConjunction#isAnd <em>And</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>And</em>' attribute.
   * @see #isAnd()
   * @generated
   */
  void setAnd(boolean value);

} // DispatchConjunction
