/**
 * (C) Multitude Corporation 2024
 * generated by Xtext 2.30.0
 *  from BLESS.xtext, by BRL
 */
package com.multitude.aadl.bless.bLESS;

import org.eclipse.emf.ecore.EObject;

import org.osate.aadl2.Element;
import org.osate.aadl2.PropertyConstant;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Non Numeric Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.multitude.aadl.bless.bLESS.NonNumericProperty#getProperty <em>Property</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.NonNumericProperty#getPropertyConstant <em>Property Constant</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.NonNumericProperty#getTod <em>Tod</em>}</li>
 * </ul>
 *
 * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getNonNumericProperty()
 * @model
 * @generated
 */
public interface NonNumericProperty extends EObject, Element
{
  /**
   * Returns the value of the '<em><b>Property</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property</em>' containment reference.
   * @see #setProperty(PropertyReference)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getNonNumericProperty_Property()
   * @model containment="true"
   * @generated
   */
  PropertyReference getProperty();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.NonNumericProperty#getProperty <em>Property</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property</em>' containment reference.
   * @see #getProperty()
   * @generated
   */
  void setProperty(PropertyReference value);

  /**
   * Returns the value of the '<em><b>Property Constant</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property Constant</em>' reference.
   * @see #setPropertyConstant(PropertyConstant)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getNonNumericProperty_PropertyConstant()
   * @model
   * @generated
   */
  PropertyConstant getPropertyConstant();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.NonNumericProperty#getPropertyConstant <em>Property Constant</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property Constant</em>' reference.
   * @see #getPropertyConstant()
   * @generated
   */
  void setPropertyConstant(PropertyConstant value);

  /**
   * Returns the value of the '<em><b>Tod</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tod</em>' containment reference.
   * @see #setTod(TypeOrReference)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getNonNumericProperty_Tod()
   * @model containment="true"
   * @generated
   */
  TypeOrReference getTod();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.NonNumericProperty#getTod <em>Tod</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tod</em>' containment reference.
   * @see #getTod()
   * @generated
   */
  void setTod(TypeOrReference value);

} // NonNumericProperty
