/**
 * (C) Multitude Corporation 2023
 * generated by Xtext 2.30.0
 *  from BLESS.xtext, by BRL
 */
package com.multitude.aadl.bless.bLESS;

import org.eclipse.emf.ecore.EObject;

import org.osate.aadl2.Element;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Otherwise</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.multitude.aadl.bless.bLESS.Otherwise#getO <em>O</em>}</li>
 * </ul>
 *
 * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getOtherwise()
 * @model
 * @generated
 */
public interface Otherwise extends EObject, Element
{
  /**
   * Returns the value of the '<em><b>O</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>O</em>' attribute.
   * @see #setO(String)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getOtherwise_O()
   * @model
   * @generated
   */
  String getO();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.Otherwise#getO <em>O</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>O</em>' attribute.
   * @see #getO()
   * @generated
   */
  void setO(String value);

} // Otherwise
