/**
 * (C) Multitude Corporation 2021
 * generated by Xtext 2.27.0
 *  from BLESS.xtext, by BRL
 */
package com.multitude.aadl.bless.bLESS;

import org.eclipse.emf.ecore.EObject;

import org.osate.aadl2.Element;
import org.osate.aadl2.Port;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Port Output</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.multitude.aadl.bless.bLESS.PortOutput#getPort <em>Port</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.PortOutput#getEor <em>Eor</em>}</li>
 * </ul>
 *
 * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getPortOutput()
 * @model
 * @generated
 */
public interface PortOutput extends EObject, Element
{
  /**
   * Returns the value of the '<em><b>Port</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' reference.
   * @see #setPort(Port)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getPortOutput_Port()
   * @model
   * @generated
   */
  Port getPort();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.PortOutput#getPort <em>Port</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' reference.
   * @see #getPort()
   * @generated
   */
  void setPort(Port value);

  /**
   * Returns the value of the '<em><b>Eor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eor</em>' containment reference.
   * @see #setEor(Expression)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getPortOutput_Eor()
   * @model containment="true"
   * @generated
   */
  Expression getEor();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.PortOutput#getEor <em>Eor</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Eor</em>' containment reference.
   * @see #getEor()
   * @generated
   */
  void setEor(Expression value);

} // PortOutput
