/**
 * (C) Multitude Corporation 2023
 * generated by Xtext 2.27.0
 *  from BLESS.xtext, by BRL
 */
package com.multitude.aadl.bless.bLESS;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.osate.aadl2.ComponentClassifier;
import org.osate.aadl2.Element;
import org.osate.aadl2.Property;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.multitude.aadl.bless.bLESS.PropertyReference#getPname <em>Pname</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.PropertyReference#getField <em>Field</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.PropertyReference#isSelf <em>Self</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.PropertyReference#getSpname <em>Spname</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.PropertyReference#getComponent <em>Component</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.PropertyReference#getCpname <em>Cpname</em>}</li>
 * </ul>
 *
 * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getPropertyReference()
 * @model
 * @generated
 */
public interface PropertyReference extends EObject, Element
{
  /**
   * Returns the value of the '<em><b>Pname</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pname</em>' reference.
   * @see #setPname(Property)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getPropertyReference_Pname()
   * @model
   * @generated
   */
  Property getPname();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.PropertyReference#getPname <em>Pname</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pname</em>' reference.
   * @see #getPname()
   * @generated
   */
  void setPname(Property value);

  /**
   * Returns the value of the '<em><b>Field</b></em>' containment reference list.
   * The list contents are of type {@link com.multitude.aadl.bless.bLESS.PropertyField}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field</em>' containment reference list.
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getPropertyReference_Field()
   * @model containment="true"
   * @generated
   */
  EList<PropertyField> getField();

  /**
   * Returns the value of the '<em><b>Self</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Self</em>' attribute.
   * @see #setSelf(boolean)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getPropertyReference_Self()
   * @model
   * @generated
   */
  boolean isSelf();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.PropertyReference#isSelf <em>Self</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Self</em>' attribute.
   * @see #isSelf()
   * @generated
   */
  void setSelf(boolean value);

  /**
   * Returns the value of the '<em><b>Spname</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Spname</em>' reference.
   * @see #setSpname(Property)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getPropertyReference_Spname()
   * @model
   * @generated
   */
  Property getSpname();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.PropertyReference#getSpname <em>Spname</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Spname</em>' reference.
   * @see #getSpname()
   * @generated
   */
  void setSpname(Property value);

  /**
   * Returns the value of the '<em><b>Component</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component</em>' reference.
   * @see #setComponent(ComponentClassifier)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getPropertyReference_Component()
   * @model
   * @generated
   */
  ComponentClassifier getComponent();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.PropertyReference#getComponent <em>Component</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Component</em>' reference.
   * @see #getComponent()
   * @generated
   */
  void setComponent(ComponentClassifier value);

  /**
   * Returns the value of the '<em><b>Cpname</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cpname</em>' reference.
   * @see #setCpname(Property)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getPropertyReference_Cpname()
   * @model
   * @generated
   */
  Property getCpname();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.PropertyReference#getCpname <em>Cpname</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cpname</em>' reference.
   * @see #getCpname()
   * @generated
   */
  void setCpname(Property value);

} // PropertyReference
