/**
 * (C) Multitude Corporation 2023
 * generated by Xtext 2.30.0
 *  from BLESS.xtext, by BRL
 */
package com.multitude.aadl.bless.bLESS;

import org.eclipse.emf.ecore.EObject;

import org.osate.aadl2.Element;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.multitude.aadl.bless.bLESS.PropertyField#getIndex <em>Index</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.PropertyField#getVariable <em>Variable</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.PropertyField#getPf <em>Pf</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.PropertyField#getUpper <em>Upper</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.PropertyField#getLower <em>Lower</em>}</li>
 * </ul>
 *
 * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getPropertyField()
 * @model
 * @generated
 */
public interface PropertyField extends EObject, Element
{
  /**
   * Returns the value of the '<em><b>Index</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index</em>' attribute.
   * @see #setIndex(String)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getPropertyField_Index()
   * @model
   * @generated
   */
  String getIndex();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.PropertyField#getIndex <em>Index</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Index</em>' attribute.
   * @see #getIndex()
   * @generated
   */
  void setIndex(String value);

  /**
   * Returns the value of the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' reference.
   * @see #setVariable(Variable)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getPropertyField_Variable()
   * @model
   * @generated
   */
  Variable getVariable();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.PropertyField#getVariable <em>Variable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(Variable value);

  /**
   * Returns the value of the '<em><b>Pf</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pf</em>' attribute.
   * @see #setPf(String)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getPropertyField_Pf()
   * @model
   * @generated
   */
  String getPf();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.PropertyField#getPf <em>Pf</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pf</em>' attribute.
   * @see #getPf()
   * @generated
   */
  void setPf(String value);

  /**
   * Returns the value of the '<em><b>Upper</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Upper</em>' attribute.
   * @see #setUpper(String)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getPropertyField_Upper()
   * @model
   * @generated
   */
  String getUpper();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.PropertyField#getUpper <em>Upper</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Upper</em>' attribute.
   * @see #getUpper()
   * @generated
   */
  void setUpper(String value);

  /**
   * Returns the value of the '<em><b>Lower</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lower</em>' attribute.
   * @see #setLower(String)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getPropertyField_Lower()
   * @model
   * @generated
   */
  String getLower();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.PropertyField#getLower <em>Lower</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lower</em>' attribute.
   * @see #getLower()
   * @generated
   */
  void setLower(String value);

} // PropertyField
