/**
 * (C) Multitude Corporation 2023
 * generated by Xtext 2.27.0
 *  from BLESS.xtext, by BRL
 */
package com.multitude.aadl.bless.bLESS;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.osate.aadl2.NamedElement;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unit Name</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.multitude.aadl.bless.bLESS.UnitName#getLongname <em>Longname</em>}</li>
 * </ul>
 *
 * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getUnitName()
 * @model
 * @generated
 */
public interface UnitName extends EObject, NamedElement
{
  /**
   * Returns the value of the '<em><b>Longname</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Longname</em>' attribute list.
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getUnitName_Longname()
   * @model unique="false"
   * @generated
   */
  EList<String> getLongname();

} // UnitName
