/**
 * (C) Multitude Corporation 2024
 * generated by Xtext 2.33.0
 *  from BLESS.xtext, by BRL
 */
package com.multitude.aadl.bless.bLESS;

import org.eclipse.emf.ecore.EObject;

import org.osate.aadl2.Element;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unit Factor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.multitude.aadl.bless.bLESS.UnitFactor#getUnit <em>Unit</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.UnitFactor#getOp <em>Op</em>}</li>
 *   <li>{@link com.multitude.aadl.bless.bLESS.UnitFactor#getFactor <em>Factor</em>}</li>
 * </ul>
 *
 * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getUnitFactor()
 * @model
 * @generated
 */
public interface UnitFactor extends EObject, Element
{
  /**
   * Returns the value of the '<em><b>Unit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' containment reference.
   * @see #setUnit(UnitName)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getUnitFactor_Unit()
   * @model containment="true"
   * @generated
   */
  UnitName getUnit();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.UnitFactor#getUnit <em>Unit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit</em>' containment reference.
   * @see #getUnit()
   * @generated
   */
  void setUnit(UnitName value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getUnitFactor_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.UnitFactor#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Factor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Factor</em>' attribute.
   * @see #setFactor(String)
   * @see com.multitude.aadl.bless.bLESS.BLESSPackage#getUnitFactor_Factor()
   * @model
   * @generated
   */
  String getFactor();

  /**
   * Sets the value of the '{@link com.multitude.aadl.bless.bLESS.UnitFactor#getFactor <em>Factor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Factor</em>' attribute.
   * @see #getFactor()
   * @generated
   */
  void setFactor(String value);

} // UnitFactor
