/*
 * (C) Multitude Corporation 2024
 * generated by Xtext 2.33.0
 from BLESS.xtext, by BRL 
 */
package com.multitude.aadl.bless.ui;

import com.google.inject.Injector;
import com.multitude.aadl.bless.ui.internal.BlessActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BLESSExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(BlessActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		BlessActivator activator = BlessActivator.getInstance();
		return activator != null ? activator.getInjector(BlessActivator.COM_MULTITUDE_AADL_BLESS_BLESS) : null;
	}

}
